# Generated by Django 3.2.8 on 2021-10-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211028_1206'),
    ]

    operations = [
        migrations.RunSQL("""
                INSERT INTO store_collection(title)
                VALUES('collection1')
            """, """
            
            DELETE FROM store_collection 
            WHERE title ='collection1'
            """


                          )
    ]
